[package]
name = "weld"
version = "0.1.0"
authors = ["Matei Zaharia <matei.zaharia@gmail.com>"]

[dependencies]
lazy_static = "0.2.1"
weld_ast = { path = "weld_ast", version = "^0.1.0" }
weld_error = { path = "weld_error", version = "^0.1.0" }
weld_parser = { path = "weld_parser", version = "^0.1.0" }
weld_transform = { path = "weld_transform", version = "^0.1.0" }

[lib]
path = "weld/lib.rs"

[[bin]]
name = "repl"
path = "weld/bin/repl.rs"

# Test our submodules too when we call cargo test at top level

[[test]]
name = "weld_ast"
path = "weld_ast/lib.rs"

[[test]]
name = "weld_transform"
path = "weld_transform/lib.rs"
