[package]
name = "weld"
version = "0.1.0"
authors = ["Matei Zaharia <matei.zaharia@gmail.com>"]

[dependencies]
lazy_static = "0.2.1"
easy_ll = { path = "easy_ll", version = "^0.1.0" }
weld_ast = { path = "weld_ast", version = "^0.1.0" }
weld_error = { path = "weld_error", version = "^0.1.0" }
weld_parser = { path = "weld_parser", version = "^0.1.0" }

[lib]
path = "weld/src/lib.rs"

[[bin]]
name = "repl"
path = "weld/src/bin/repl.rs"
